# Generated by Django 4.1.7 on 2023-06-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CisDf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corp", models.TextField(blank=True, null=True)),
                ("account", models.TextField(blank=True, null=True)),
                ("account_detail", models.TextField(blank=True, null=True)),
                ("account_detail_2", models.TextField(blank=True, null=True)),
                (
                    "number_2018",
                    models.FloatField(blank=True, db_column="2018", null=True),
                ),
                (
                    "number_2019",
                    models.FloatField(blank=True, db_column="2019", null=True),
                ),
                (
                    "number_2020",
                    models.FloatField(blank=True, db_column="2020", null=True),
                ),
                (
                    "number_2021",
                    models.FloatField(blank=True, db_column="2021", null=True),
                ),
                (
                    "number_2022",
                    models.FloatField(blank=True, db_column="2022", null=True),
                ),
            ],
            options={
                "db_table": "cis_df",
            },
        ),
        migrations.CreateModel(
            name="CompanyName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standard_code",
                    models.CharField(
                        db_column="Standard_code", max_length=20, unique=True
                    ),
                ),
                (
                    "short_code",
                    models.TextField(blank=True, db_column="Short_code", null=True),
                ),
                (
                    "company_full_name",
                    models.TextField(
                        blank=True, db_column="Company_full_name", null=True
                    ),
                ),
                (
                    "company_name",
                    models.TextField(blank=True, db_column="Company_name", null=True),
                ),
            ],
            options={
                "db_table": "company_name",
            },
        ),
    ]
