# Generated by Django 2.1.7 on 2023-07-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_address_phonenumber_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp', models.TextField(blank=True, null=True)),
                ('stock_code', models.TextField(blank=True, null=True)),
                ('count', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('paywellfare', models.FloatField(blank=True, null=True)),
                ('worklifebal', models.FloatField(blank=True, null=True)),
                ('culture', models.FloatField(blank=True, null=True)),
                ('opportunity', models.FloatField(blank=True, null=True)),
                ('manager', models.FloatField(blank=True, null=True)),
                ('recommend', models.FloatField(blank=True, null=True)),
                ('ceo', models.FloatField(blank=True, null=True)),
                ('potential', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating',
            },
        ),
    ]
