# Generated by Django 2.1.7 on 2023-07-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_address_phonenumber_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.TextField(blank=True, null=True)),
                ('jobp_rating', models.FloatField(blank=True, null=True)),
                ('jobp_paywellfare', models.FloatField(blank=True, null=True)),
                ('jobp_worklifebal', models.FloatField(blank=True, null=True)),
                ('jobp_culture', models.FloatField(blank=True, null=True)),
                ('jobp_opportunity', models.FloatField(blank=True, null=True)),
                ('jobp_manager', models.FloatField(blank=True, null=True)),
                ('jobp_recommend', models.FloatField(blank=True, null=True)),
                ('jobp_ceo', models.FloatField(blank=True, null=True)),
                ('jobp_potential', models.FloatField(blank=True, null=True)),
                ('jobp_cnt', models.FloatField(blank=True, null=True)),
                ('blind_rating', models.FloatField(blank=True, null=True)),
                ('blind_cnt', models.FloatField(blank=True, null=True)),
                ('blind_opportunity', models.FloatField(blank=True, null=True)),
                ('blind_worklifebal', models.FloatField(blank=True, null=True)),
                ('blind_paywellfare', models.FloatField(blank=True, null=True)),
                ('blind_culture', models.FloatField(blank=True, null=True)),
                ('blind_manager', models.FloatField(blank=True, null=True)),
                ('corp', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating_data',
            },
        ),
    ]
