# Generated by Django 2.1.7 on 2023-07-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_investmentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp', models.TextField(blank=True, null=True)),
                ('stock_code', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('label_en', models.TextField(blank=True, null=True)),
                ('label_ko', models.TextField(blank=True, null=True)),
                ('number_2018', models.FloatField(blank=True, db_column='2018', null=True)),
                ('number_2019', models.FloatField(blank=True, db_column='2019', null=True)),
                ('number_2020', models.FloatField(blank=True, db_column='2020', null=True)),
                ('number_2021', models.FloatField(blank=True, db_column='2021', null=True)),
                ('number_2022', models.FloatField(blank=True, db_column='2022', null=True)),
                ('yoy', models.FloatField(blank=True, db_column='YoY', null=True)),
            ],
            options={
                'db_table': 'credit_data',
            },
        ),
    ]
