# Generated by Django 2.1.7 on 2023-07-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_visualization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('profitability', models.FloatField(blank=True, null=True)),
                ('growth', models.FloatField(blank=True, null=True)),
                ('stability', models.FloatField(blank=True, null=True)),
                ('activity', models.FloatField(blank=True, null=True)),
                ('valuation', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_investment',
            },
        ),
        migrations.CreateModel(
            name='IndustryInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.TextField(blank=True, null=True)),
                ('profitability', models.FloatField(blank=True, null=True)),
                ('growth', models.FloatField(blank=True, null=True)),
                ('stability', models.FloatField(blank=True, null=True)),
                ('activity', models.FloatField(blank=True, null=True)),
                ('valuation', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'industry_investment',
            },
        ),
    ]
